spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/todo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      cache-null-values: true
      time-to-live: 60000
server:
  port: 3129
